import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { pageHead } from "@/lib/page-head";
import {
  DataTable,
  DefinitionList,
  FilterBar,
  FormGrid,
  GhostButton,
  GoldButton,
  PageHeader,
  Panel,
  Timeline,
} from "@/components/adex/kit";
import { sellerStones } from "@/lib/adex-data";

export const Route = createFileRoute("/seller/stones/")({
  head: pageHead(
    "My Stones | ADEX Seller Portal",
    "Register stones against a barcode, track ADEX Stone IDs, valuation, auction, shipment, payment and certification from one record.",
  ),
  component: SellerStones,
});

function SellerStones() {
  const [submitted, setSubmitted] = useState(false);

  return (
    <>
      <PageHeader
        title="My Stones"
        description="Every stone registered by your organization. Open a Stone ID to see valuation, auction, shipment, payment and certificates in one record."
        actions={<GoldButton onClick={() => setSubmitted(false)}>Register stone</GoldButton>}
      />

      <FilterBar fields={["Stone ID", "Barcode", "Carat", "Status", "Valuation"]} />
      <DataTable rows={sellerStones} linkBase="seller" />

      {submitted ? (
        <Panel title="Registration submitted" className="mt-6">
          <p className="text-sm text-muted-foreground">
            Your submission has been accepted and an ADEX Stone ID has been issued. This is how the
            entry now looks — everything that follows (valuation, auction, shipment, payment,
            certificates) is tracked on that one record.
          </p>
          <div className="mt-4 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
            <DefinitionList
              items={[
                { label: "ADEX Stone ID", value: "ADX-S-04388" },
                { label: "Barcode", value: "8842-1163" },
                { label: "Weight / carat", value: "3.24 ct" },
                { label: "Status", value: "Submitted — awaiting receipt" },
              ]}
            />
            <Timeline
              steps={[
                { label: "Submitted", detail: "Registration received", done: true },
                { label: "ADEX Stone ID issued", detail: "ADX-S-04388", done: true },
                { label: "Receiving & scanning", detail: "Operated by ADEX", done: false },
                { label: "Valuation", detail: "After scan", done: false },
              ]}
            />
          </div>
          <div className="mt-4 flex gap-2">
            <Link
              to="/seller/stones/$stoneId"
              params={{ stoneId: "ADX-S-04388" }}
              className="h-9 rounded-sm bg-gold px-4 text-sm leading-9 font-semibold text-gold-foreground hover:opacity-90"
            >
              Open stone record
            </Link>
            <GhostButton onClick={() => setSubmitted(false)}>Register another</GhostButton>
          </div>
        </Panel>
      ) : (
        <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
          <Panel title="Register stone">
            <FormGrid
              fields={[
                { label: "Barcode" },
                { label: "Weight / carat" },
                { label: "Classification" },
                { label: "Collection location" },
                { label: "Source reference" },
                { label: "Lot association" },
                { label: "Images", type: "file" },
                { label: "Initial metadata", type: "textarea" },
              ]}
            />
            <div className="mt-4 flex gap-2">
              <GoldButton onClick={() => setSubmitted(true)}>Submit registration</GoldButton>
              <GhostButton>Save draft</GhostButton>
            </div>
            <p className="mt-3 text-xs text-muted-foreground">
              Made a mistake? Registrations stay editable until the stone is valued or listed — open
              the stone record and use Edit registration.
            </p>
          </Panel>

          <Panel title="Identity flow">
            <Timeline
              steps={[
                { label: "Barcode", detail: "Scanned at collection point", done: true },
                { label: "ADEX Stone ID", detail: "Generated by the platform", done: true },
                { label: "Stone record", detail: "Full lifecycle history opens", done: true },
                { label: "Receiving & scanning", detail: "Operated by ADEX, view only", done: false },
              ]}
            />
          </Panel>
        </div>
      )}
    </>
  );
}
