/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BuyerRouteRouteImport } from './routes/buyer/route'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuctionsRouteImport } from './routes/admin/auctions'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminIntakeRouteImport } from './routes/admin/intake'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminLogisticsRouteImport } from './routes/admin/logistics'
import { Route as AdminNewAuctionRouteImport } from './routes/admin/new-auction'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminRegisterUserRouteImport } from './routes/admin/register-user'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminValuationRouteImport } from './routes/admin/valuation'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as BuyerAnalysisRouteImport } from './routes/buyer/analysis'
import { Route as BuyerBidsRouteImport } from './routes/buyer/bids'
import { Route as BuyerCheckoutRouteImport } from './routes/buyer/checkout'
import { Route as BuyerInventoryRouteImport } from './routes/buyer/inventory'
import { Route as BuyerKycRouteImport } from './routes/buyer/kyc'
import { Route as BuyerMarketplaceRouteImport } from './routes/buyer/marketplace'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer/notifications'
import { Route as BuyerOrdersRouteImport } from './routes/buyer/orders'
import { Route as BuyerPaymentsRouteImport } from './routes/buyer/payments'
import { Route as BuyerProfileRouteImport } from './routes/buyer/profile'
import { Route as BuyerPurchasesRouteImport } from './routes/buyer/purchases'
import { Route as BuyerReturnsRouteImport } from './routes/buyer/returns'
import { Route as BuyerShipmentsRouteImport } from './routes/buyer/shipments'
import { Route as BuyerShowroomRouteImport } from './routes/buyer/showroom'
import { Route as BuyerWatchlistRouteImport } from './routes/buyer/watchlist'
import { Route as HouseHouseRouteImport } from './routes/house.$house'
import { Route as ListingListingIdRouteImport } from './routes/listing.$listingId'
import { Route as LotsLotIdRouteImport } from './routes/lots/$lotId'
import { Route as StonesStoneIdRouteImport } from './routes/stones/$stoneId'
import { Route as AdminLotLotIdRouteImport } from './routes/admin/lot/$lotId'
import { Route as AdminLotsLotIdRouteImport } from './routes/admin/lots/$lotId'
import { Route as AdminStoneStoneIdRouteImport } from './routes/admin/stone/$stoneId'
import { Route as AdminStonesIndexRouteImport } from './routes/admin/stones/index'
import { Route as AdminStonesStoneIdRouteImport } from './routes/admin/stones/$stoneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRouteRoute = BuyerRouteRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewAuctionRoute = AdminNewAuctionRouteImport.update({
  id: '/new-auction',
  path: '/new-auction',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterUserRoute = AdminRegisterUserRouteImport.update({
  id: '/register-user',
  path: '/register-user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminValuationRoute = AdminValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerAnalysisRoute = BuyerAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerBidsRoute = BuyerBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerCheckoutRoute = BuyerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerInventoryRoute = BuyerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerKycRoute = BuyerKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerMarketplaceRoute = BuyerMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerPaymentsRoute = BuyerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerPurchasesRoute = BuyerPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerReturnsRoute = BuyerReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerShipmentsRoute = BuyerShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerShowroomRoute = BuyerShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const BuyerWatchlistRoute = BuyerWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => BuyerRouteRoute,
} as any)
const HouseHouseRoute = HouseHouseRouteImport.update({
  id: '/house/$house',
  path: '/house/$house',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsLotIdRoute = LotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const StonesStoneIdRoute = StonesStoneIdRouteImport.update({
  id: '/stones/$stoneId',
  path: '/stones/$stoneId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLotLotIdRoute = AdminLotLotIdRouteImport.update({
  id: '/lot/$lotId',
  path: '/lot/$lotId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLotsLotIdRoute = AdminLotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoneStoneIdRoute = AdminStoneStoneIdRouteImport.update({
  id: '/stone/$stoneId',
  path: '/stone/$stoneId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStonesIndexRoute = AdminStonesIndexRouteImport.update({
  id: '/stones/',
  path: '/stones/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStonesStoneIdRoute = AdminStonesStoneIdRouteImport.update({
  id: '/stones/$stoneId',
  path: '/stones/$stoneId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/buyer': typeof BuyerRouteRouteWithChildren
  '/browse': typeof BrowseRoute
  '/collection': typeof CollectionRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/new-auction': typeof AdminNewAuctionRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register-user': typeof AdminRegisterUserRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/valuation': typeof AdminValuationRoute
  '/buyer/analysis': typeof BuyerAnalysisRoute
  '/buyer/bids': typeof BuyerBidsRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/inventory': typeof BuyerInventoryRoute
  '/buyer/kyc': typeof BuyerKycRoute
  '/buyer/marketplace': typeof BuyerMarketplaceRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/payments': typeof BuyerPaymentsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/purchases': typeof BuyerPurchasesRoute
  '/buyer/returns': typeof BuyerReturnsRoute
  '/buyer/shipments': typeof BuyerShipmentsRoute
  '/buyer/showroom': typeof BuyerShowroomRoute
  '/buyer/watchlist': typeof BuyerWatchlistRoute
  '/house/$house': typeof HouseHouseRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/stones/$stoneId': typeof StonesStoneIdRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/admin/lot/$lotId': typeof AdminLotLotIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/stone/$stoneId': typeof AdminStoneStoneIdRoute
  '/admin/stones/$stoneId': typeof AdminStonesStoneIdRoute
  '/admin/stones/': typeof AdminStonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collection': typeof CollectionRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/new-auction': typeof AdminNewAuctionRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register-user': typeof AdminRegisterUserRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/valuation': typeof AdminValuationRoute
  '/buyer/analysis': typeof BuyerAnalysisRoute
  '/buyer/bids': typeof BuyerBidsRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/inventory': typeof BuyerInventoryRoute
  '/buyer/kyc': typeof BuyerKycRoute
  '/buyer/marketplace': typeof BuyerMarketplaceRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/payments': typeof BuyerPaymentsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/purchases': typeof BuyerPurchasesRoute
  '/buyer/returns': typeof BuyerReturnsRoute
  '/buyer/shipments': typeof BuyerShipmentsRoute
  '/buyer/showroom': typeof BuyerShowroomRoute
  '/buyer/watchlist': typeof BuyerWatchlistRoute
  '/house/$house': typeof HouseHouseRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/stones/$stoneId': typeof StonesStoneIdRoute
  '/admin': typeof AdminIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/admin/lot/$lotId': typeof AdminLotLotIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/stone/$stoneId': typeof AdminStoneStoneIdRoute
  '/admin/stones/$stoneId': typeof AdminStonesStoneIdRoute
  '/admin/stones': typeof AdminStonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/buyer': typeof BuyerRouteRouteWithChildren
  '/browse': typeof BrowseRoute
  '/collection': typeof CollectionRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/new-auction': typeof AdminNewAuctionRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register-user': typeof AdminRegisterUserRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/valuation': typeof AdminValuationRoute
  '/buyer/analysis': typeof BuyerAnalysisRoute
  '/buyer/bids': typeof BuyerBidsRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/inventory': typeof BuyerInventoryRoute
  '/buyer/kyc': typeof BuyerKycRoute
  '/buyer/marketplace': typeof BuyerMarketplaceRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/payments': typeof BuyerPaymentsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/purchases': typeof BuyerPurchasesRoute
  '/buyer/returns': typeof BuyerReturnsRoute
  '/buyer/shipments': typeof BuyerShipmentsRoute
  '/buyer/showroom': typeof BuyerShowroomRoute
  '/buyer/watchlist': typeof BuyerWatchlistRoute
  '/house/$house': typeof HouseHouseRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/stones/$stoneId': typeof StonesStoneIdRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/admin/lot/$lotId': typeof AdminLotLotIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/stone/$stoneId': typeof AdminStoneStoneIdRoute
  '/admin/stones/$stoneId': typeof AdminStonesStoneIdRoute
  '/admin/stones/': typeof AdminStonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buyer'
    | '/browse'
    | '/collection'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/admin/auctions'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/kyc'
    | '/admin/logistics'
    | '/admin/new-auction'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/register-user'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/valuation'
    | '/buyer/analysis'
    | '/buyer/bids'
    | '/buyer/checkout'
    | '/buyer/inventory'
    | '/buyer/kyc'
    | '/buyer/marketplace'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/payments'
    | '/buyer/profile'
    | '/buyer/purchases'
    | '/buyer/returns'
    | '/buyer/shipments'
    | '/buyer/showroom'
    | '/buyer/watchlist'
    | '/house/$house'
    | '/listing/$listingId'
    | '/lots/$lotId'
    | '/stones/$stoneId'
    | '/admin/'
    | '/buyer/'
    | '/admin/lot/$lotId'
    | '/admin/lots/$lotId'
    | '/admin/stone/$stoneId'
    | '/admin/stones/$stoneId'
    | '/admin/stones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/collection'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/admin/auctions'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/kyc'
    | '/admin/logistics'
    | '/admin/new-auction'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/register-user'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/valuation'
    | '/buyer/analysis'
    | '/buyer/bids'
    | '/buyer/checkout'
    | '/buyer/inventory'
    | '/buyer/kyc'
    | '/buyer/marketplace'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/payments'
    | '/buyer/profile'
    | '/buyer/purchases'
    | '/buyer/returns'
    | '/buyer/shipments'
    | '/buyer/showroom'
    | '/buyer/watchlist'
    | '/house/$house'
    | '/listing/$listingId'
    | '/lots/$lotId'
    | '/stones/$stoneId'
    | '/admin'
    | '/buyer'
    | '/admin/lot/$lotId'
    | '/admin/lots/$lotId'
    | '/admin/stone/$stoneId'
    | '/admin/stones/$stoneId'
    | '/admin/stones'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buyer'
    | '/browse'
    | '/collection'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/admin/auctions'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/kyc'
    | '/admin/logistics'
    | '/admin/new-auction'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/register-user'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/valuation'
    | '/buyer/analysis'
    | '/buyer/bids'
    | '/buyer/checkout'
    | '/buyer/inventory'
    | '/buyer/kyc'
    | '/buyer/marketplace'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/payments'
    | '/buyer/profile'
    | '/buyer/purchases'
    | '/buyer/returns'
    | '/buyer/shipments'
    | '/buyer/showroom'
    | '/buyer/watchlist'
    | '/house/$house'
    | '/listing/$listingId'
    | '/lots/$lotId'
    | '/stones/$stoneId'
    | '/admin/'
    | '/buyer/'
    | '/admin/lot/$lotId'
    | '/admin/lots/$lotId'
    | '/admin/stone/$stoneId'
    | '/admin/stones/$stoneId'
    | '/admin/stones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BuyerRouteRoute: typeof BuyerRouteRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CollectionRoute: typeof CollectionRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  HouseHouseRoute: typeof HouseHouseRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
  LotsLotIdRoute: typeof LotsLotIdRoute
  StonesStoneIdRoute: typeof StonesStoneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/new-auction': {
      id: '/admin/new-auction'
      path: '/new-auction'
      fullPath: '/admin/new-auction'
      preLoaderRoute: typeof AdminNewAuctionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register-user': {
      id: '/admin/register-user'
      path: '/register-user'
      fullPath: '/admin/register-user'
      preLoaderRoute: typeof AdminRegisterUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/valuation': {
      id: '/admin/valuation'
      path: '/valuation'
      fullPath: '/admin/valuation'
      preLoaderRoute: typeof AdminValuationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/analysis': {
      id: '/buyer/analysis'
      path: '/analysis'
      fullPath: '/buyer/analysis'
      preLoaderRoute: typeof BuyerAnalysisRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/bids': {
      id: '/buyer/bids'
      path: '/bids'
      fullPath: '/buyer/bids'
      preLoaderRoute: typeof BuyerBidsRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/inventory': {
      id: '/buyer/inventory'
      path: '/inventory'
      fullPath: '/buyer/inventory'
      preLoaderRoute: typeof BuyerInventoryRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/kyc': {
      id: '/buyer/kyc'
      path: '/kyc'
      fullPath: '/buyer/kyc'
      preLoaderRoute: typeof BuyerKycRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/marketplace': {
      id: '/buyer/marketplace'
      path: '/marketplace'
      fullPath: '/buyer/marketplace'
      preLoaderRoute: typeof BuyerMarketplaceRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/payments': {
      id: '/buyer/payments'
      path: '/payments'
      fullPath: '/buyer/payments'
      preLoaderRoute: typeof BuyerPaymentsRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/purchases': {
      id: '/buyer/purchases'
      path: '/purchases'
      fullPath: '/buyer/purchases'
      preLoaderRoute: typeof BuyerPurchasesRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/returns': {
      id: '/buyer/returns'
      path: '/returns'
      fullPath: '/buyer/returns'
      preLoaderRoute: typeof BuyerReturnsRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/shipments': {
      id: '/buyer/shipments'
      path: '/shipments'
      fullPath: '/buyer/shipments'
      preLoaderRoute: typeof BuyerShipmentsRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/showroom': {
      id: '/buyer/showroom'
      path: '/showroom'
      fullPath: '/buyer/showroom'
      preLoaderRoute: typeof BuyerShowroomRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/buyer/watchlist': {
      id: '/buyer/watchlist'
      path: '/watchlist'
      fullPath: '/buyer/watchlist'
      preLoaderRoute: typeof BuyerWatchlistRouteImport
      parentRoute: typeof BuyerRouteRoute
    }
    '/house/$house': {
      id: '/house/$house'
      path: '/house/$house'
      fullPath: '/house/$house'
      preLoaderRoute: typeof HouseHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$lotId': {
      id: '/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/lots/$lotId'
      preLoaderRoute: typeof LotsLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stones/$stoneId': {
      id: '/stones/$stoneId'
      path: '/stones/$stoneId'
      fullPath: '/stones/$stoneId'
      preLoaderRoute: typeof StonesStoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lot/$lotId': {
      id: '/admin/lot/$lotId'
      path: '/lot/$lotId'
      fullPath: '/admin/lot/$lotId'
      preLoaderRoute: typeof AdminLotLotIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lots/$lotId': {
      id: '/admin/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/admin/lots/$lotId'
      preLoaderRoute: typeof AdminLotsLotIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stone/$stoneId': {
      id: '/admin/stone/$stoneId'
      path: '/stone/$stoneId'
      fullPath: '/admin/stone/$stoneId'
      preLoaderRoute: typeof AdminStoneStoneIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stones/': {
      id: '/admin/stones/'
      path: '/stones'
      fullPath: '/admin/stones/'
      preLoaderRoute: typeof AdminStonesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stones/$stoneId': {
      id: '/admin/stones/$stoneId'
      path: '/stones/$stoneId'
      fullPath: '/admin/stones/$stoneId'
      preLoaderRoute: typeof AdminStonesStoneIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminNewAuctionRoute: typeof AdminNewAuctionRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegisterUserRoute: typeof AdminRegisterUserRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminValuationRoute: typeof AdminValuationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLotLotIdRoute: typeof AdminLotLotIdRoute
  AdminLotsLotIdRoute: typeof AdminLotsLotIdRoute
  AdminStoneStoneIdRoute: typeof AdminStoneStoneIdRoute
  AdminStonesStoneIdRoute: typeof AdminStonesStoneIdRoute
  AdminStonesIndexRoute: typeof AdminStonesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminNewAuctionRoute: AdminNewAuctionRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegisterUserRoute: AdminRegisterUserRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminValuationRoute: AdminValuationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLotLotIdRoute: AdminLotLotIdRoute,
  AdminLotsLotIdRoute: AdminLotsLotIdRoute,
  AdminStoneStoneIdRoute: AdminStoneStoneIdRoute,
  AdminStonesStoneIdRoute: AdminStonesStoneIdRoute,
  AdminStonesIndexRoute: AdminStonesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BuyerRouteRouteChildren {
  BuyerAnalysisRoute: typeof BuyerAnalysisRoute
  BuyerBidsRoute: typeof BuyerBidsRoute
  BuyerCheckoutRoute: typeof BuyerCheckoutRoute
  BuyerInventoryRoute: typeof BuyerInventoryRoute
  BuyerKycRoute: typeof BuyerKycRoute
  BuyerMarketplaceRoute: typeof BuyerMarketplaceRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  BuyerPaymentsRoute: typeof BuyerPaymentsRoute
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerPurchasesRoute: typeof BuyerPurchasesRoute
  BuyerReturnsRoute: typeof BuyerReturnsRoute
  BuyerShipmentsRoute: typeof BuyerShipmentsRoute
  BuyerShowroomRoute: typeof BuyerShowroomRoute
  BuyerWatchlistRoute: typeof BuyerWatchlistRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
}

const BuyerRouteRouteChildren: BuyerRouteRouteChildren = {
  BuyerAnalysisRoute: BuyerAnalysisRoute,
  BuyerBidsRoute: BuyerBidsRoute,
  BuyerCheckoutRoute: BuyerCheckoutRoute,
  BuyerInventoryRoute: BuyerInventoryRoute,
  BuyerKycRoute: BuyerKycRoute,
  BuyerMarketplaceRoute: BuyerMarketplaceRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  BuyerPaymentsRoute: BuyerPaymentsRoute,
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerPurchasesRoute: BuyerPurchasesRoute,
  BuyerReturnsRoute: BuyerReturnsRoute,
  BuyerShipmentsRoute: BuyerShipmentsRoute,
  BuyerShowroomRoute: BuyerShowroomRoute,
  BuyerWatchlistRoute: BuyerWatchlistRoute,
  BuyerIndexRoute: BuyerIndexRoute,
}

const BuyerRouteRouteWithChildren = BuyerRouteRoute._addFileChildren(
  BuyerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BuyerRouteRoute: BuyerRouteRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CollectionRoute: CollectionRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  HouseHouseRoute: HouseHouseRoute,
  ListingListingIdRoute: ListingListingIdRoute,
  LotsLotIdRoute: LotsLotIdRoute,
  StonesStoneIdRoute: StonesStoneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
